-- ============ TABELAS ============
create table public.categorias (
  id bigint generated by default as identity primary key,
  nome text not null,
  tipo text not null check (tipo in ('receita', 'despesa')),
  created_at timestamptz not null default now()
);

create table public.transacoes (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  descricao text not null,
  valor numeric(12,2) not null check (valor > 0),
  tipo text not null check (tipo in ('receita', 'despesa')),
  categoria_id bigint references public.categorias(id),
  data date not null default current_date,
  observacao text,
  created_at timestamptz not null default now()
);

-- ============ SEGURANCA (RLS) ============
-- Sem isso, qualquer pessoa com a chave publica consegue ler/apagar os dados de todos.
alter table public.categorias enable row level security;
alter table public.transacoes enable row level security;

-- Categorias: qualquer usuario logado pode ver
create policy "categorias: leitura para logados"
  on public.categorias for select
  to authenticated
  using (true);

-- Transacoes: cada usuario so ve e mexe nas proprias
create policy "transacoes: ver as proprias"
  on public.transacoes for select
  to authenticated
  using (auth.uid() = user_id);

create policy "transacoes: inserir as proprias"
  on public.transacoes for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "transacoes: editar as proprias"
  on public.transacoes for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "transacoes: apagar as proprias"
  on public.transacoes for delete
  to authenticated
  using (auth.uid() = user_id);

-- ============ CATEGORIAS INICIAIS ============
insert into public.categorias (nome, tipo) values
  ('Salário', 'receita'),
  ('Freela', 'receita'),
  ('Investimentos', 'receita'),
  ('Outros', 'receita'),
  ('Alimentação', 'despesa'),
  ('Transporte', 'despesa'),
  ('Moradia', 'despesa'),
  ('Lazer', 'despesa'),
  ('Saúde', 'despesa'),
  ('Estudos', 'despesa'),
  ('Outros', 'despesa');
